### PR TITLE
Blinken

### PR DESCRIPTION
**Pull request by edelmanjm**
Seems like this should be merged it looks like a nice wrapper

### CODE REVIEW

**Comment by RobinsonZ** [comment]
Agreed, and there’s no reason it shouldn’t work, but it’s untested and we won’t be able to test it until Pandora gets back. Let’s wait on merging until then.

**Comment by edelmanjm** [comment]
Should we add functionality to keep track of the colors as well?

**Comment by RobinsonZ** [comment]
Shouldn't be too hard–`Sparks` (which is what this wrapper is based on) have a `get()` method and we can just return the corresponding enum.

**Comment by edelmanjm** [comment]
I'm under the impression the color potentiometers aren't accessible through software?

**Comment by RobinsonZ** [comment]
Oh yeah, the potentiometer values aren't accessible. I thought you meant the current mode over PWM.

**Comment by edelmanjm** [comment]
> Might be nice, but the inability to get the colors from the potentiometers seems like it'd make things kinda hard.
Hrmmm...

**Comment by RobinsonZ** [comment]
I meant the currently set mode (fire, waves, etc.). Not sure how useful that would be though.

**Pull request merged**
