### PR TITLE
Create StrictDPad

### PR DESCRIPTION
**Pull request by RobinsonZ**
Mostly written on Pandora. Ends up fixing some issues with the super-mushy D-Pad on the 360 controller.

### CODE REVIEW

**Comment by edelmanjm** [comment]
> super-mushy D-Pad
Xbox One controller? :D

**Comment by RobinsonZ** [comment]
I know, but we only have one so that's iffy. You can try to convince Alexander

**Comment by edelmanjm** [comment]
eh I was more joking the cable would probably fall out

**Comment by RobinsonZ** [comment]
Will release 0.9.0 when #66 is merged.

**Pull request merged**
