### PR TITLE
Add JITPACK environment variable

### PR DESCRIPTION
**Pull request by RobinsonZ**
This makes Gradle think it's building on JitPack when it's building on Travis, so it doesn't create a "fat jar" with everything in it.

### CODE REVIEW

**Comment by edelmanjm** [comment]
I'm confused. What's the point of this?

**Comment by RobinsonZ** [comment]
We have the buildscript setup to include all the dependencies (WPILib etc.) into one jar when deploying to robots, but to leave out dependencies when building on JitPack (by checking the `JITPACK` environment variable. This just tells Travis to have a `JITPACK` environment variable as well, to stop an oversized jar from being created. 
This may end up mattering if we add more steps to our build process for whatever reason.

**Comment by edelmanjm** [comment]
Hrm. I'd think that the Travis build should be as close to the real thing as possible, but eh.

**Comment by RobinsonZ** [comment]
I don't know, since test robots and where exactly the robot class is pointing to changes so much build-to-build and personally for me isn't even uploaded.

**Pull request merged**
